### ISSUE TITLE
Deploy docs fails because Github Pages is not enabled.

### ISSUE THREAD

**Issue by sol-vin** [D-Shwagginz/raylib_pong#3]
Enable Github Pages and select the `gh-pages` branch.

Start from number 3, do not make a new repo. Go to 8.
https://docs.github.com/en/pages/quickstart

Also go to Actions -> General and then enable read write permissions.

You can access your new docs site but going to the link they give you.

**Comment by D-Shwagginz** [comment]
ligmA
